language: generic 
sudo: required
services:
    - docker 


before-install: 
    - docker build -t varunchillara/pokemondocker -f Dockerfile.dev .


script:
    - docker run -e CI=true varunchillara/pokemondocker npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "pokemondocker"
    env: "pokemondocker-env"
    bucket-name: "elasticbeanstalk-us-east-1-696925498914"
    bucket_path: "pokemondocker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    
